version: "3"

services:

    bdd:
        image: mysql:5.7.30
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - "MYSQL_ROOT_PASSWORD="
            - "MYSQL_USER="
            - "MYSQL_PASSWORD="
            - "MYSQL_DATABASE="
        volumes: 
            - /cheminDuProjetLocal:/var/lib/mysql