version: "3"

services:

    bdd:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD="
            - "MYSQL_USER="
            - "MYSQL_PASSWORD="
            - "MYSQL_DATABASE="
        volumes: 
            - /cheminDuProjetLocal:/var/lib/mysql